"""Read-only JSON API for the dashboard (Phase 6).

Every endpoint here is a **GET**.  There is no route that changes an incident,
runs a scan, calls a provider, or touches the host: the dashboard is for
visibility and investigation, and a read-only API is the cheapest way to
guarantee that.  (It also means there is no state-changing endpoint to protect
against CSRF -- the safest kind of protection there is.)

Responses are built by :mod:`sentinelforge.dashboard.serializers`, so no
internal Python object is ever exposed and the wire format stays stable.  List
endpoints are always paginated and always bounded.
"""

from __future__ import annotations

import logging
import re
import sqlite3

from flask import Blueprint, current_app, jsonify, request

from ..models.event import Severity, parse_timestamp
from ..models.incident import IncidentStatus
from .serializers import (
    API_VERSION,
    incident_alerts,
    mitre_breakdown,
    serialize_ai_analysis,
    serialize_attack_chain,
    serialize_incident_detail,
    serialize_incident_summary,
    serialize_network,
    serialize_process_tree,
    serialize_stats,
    serialize_timeline,
    sort_key,
)

LOGGER = logging.getLogger(__name__)

api = Blueprint("api", __name__, url_prefix="/api")

#: Incident ids are generated by SentinelForge and always look like this.
#: Anything else is a malformed request (400), not a missing incident (404).
INCIDENT_ID_PATTERN = re.compile(r"^INC-\d{1,12}$")

DEFAULT_LIMIT = 50


def context():
    """The :class:`DashboardContext` attached to the running app."""
    return current_app.extensions["sentinelforge"]


# --------------------------------------------------------------------------
# Errors -- one JSON envelope for every failure, with a real status code.
# --------------------------------------------------------------------------
def error(status: int, code: str, message: str, **extra):
    payload = {"error": {"code": code, "message": message, "status": status}}
    payload["error"].update(extra)
    return jsonify(payload), status


@api.errorhandler(404)
def _not_found(exc):  # pragma: no cover - Flask's own 404 for unknown API paths
    return error(404, "not_found", "no such API endpoint")


@api.errorhandler(500)
def _server_error(exc):  # pragma: no cover - defensive
    LOGGER.exception("unhandled error in the dashboard API")
    return error(500, "internal_error", "the dashboard failed to serve this request")


# --------------------------------------------------------------------------
# Query-parameter helpers
# --------------------------------------------------------------------------
class BadRequest(ValueError):
    """A query parameter was not usable."""


def _int_arg(name: str, default: int | None = None, minimum: int | None = None,
             maximum: int | None = None) -> int | None:
    raw = request.args.get(name)
    if raw is None or raw == "":
        return default
    try:
        value = int(raw)
    except ValueError:
        raise BadRequest(f"{name} must be an integer, got {raw!r}") from None
    if minimum is not None and value < minimum:
        raise BadRequest(f"{name} must be >= {minimum}")
    if maximum is not None and value > maximum:
        value = maximum
    return value


def _choice_arg(name: str, allowed) -> str | None:
    value = request.args.get(name)
    if value in (None, "", "all"):
        return None
    if value not in allowed:
        raise BadRequest(f"{name} must be one of: {', '.join(allowed)}")
    return value


def _pagination():
    limit = _int_arg("limit", DEFAULT_LIMIT, minimum=1, maximum=context().config.max_page_size)
    offset = _int_arg("offset", 0, minimum=0)
    return limit, offset


def _page(items: list, limit: int, offset: int, **extra) -> dict:
    window = items[offset : offset + limit]
    payload = {
        "items": window,
        "total": len(items),
        "count": len(window),
        "limit": limit,
        "offset": offset,
        "has_more": offset + len(window) < len(items),
        "api_version": API_VERSION,
    }
    payload.update(extra)
    return payload


@api.errorhandler(BadRequest)
def _bad_request(exc: BadRequest):
    return error(400, "bad_request", str(exc))


def _matches_text(haystack, needle: str) -> bool:
    """Case-insensitive substring search over a few fields, done server-side."""
    needle = needle.lower()
    for value in haystack:
        if value and needle in str(value).lower():
            return True
    return False


def _load_incidents(limit_rows: int | None = None):
    """Read incidents from the Phase 3 store.  Never caches: always current."""
    with context().store() as store:
        return store.list_incidents(limit=limit_rows)


# --------------------------------------------------------------------------
# Health and statistics
# --------------------------------------------------------------------------
@api.get("/health")
def health():
    """Liveness plus a short self-description.  Never exposes a secret."""
    ctx = context()
    database_ok = True
    incident_total = 0
    try:
        with ctx.store() as store:
            incident_total = store.count()
    except sqlite3.Error as exc:
        database_ok = False
        LOGGER.warning("health check could not read the incident store: %s", exc)
    return jsonify(
        {
            "status": "ok" if database_ok else "degraded",
            "api_version": API_VERSION,
            "demo": ctx.config.demo,
            "database": {
                "path": ctx.config.resolved_db_path(),
                "readable": database_ok,
                "incidents": incident_total,
            },
            "live": {
                "subscribers": ctx.bus.subscriber_count,
                "published": ctx.bus.published,
            },
            "monitors": ctx.monitors.describe() if ctx.monitors else [],
        }
    )


@api.get("/stats")
def stats():
    """Overview counters: incidents by severity and status, plus live rates."""
    ctx = context()
    try:
        with ctx.store() as store:
            severity_counts = store.severity_counts()
            status_counts = store.status_counts()
            total = store.count()
    except sqlite3.Error as exc:
        return error(503, "store_unavailable", f"cannot read the incident store: {exc}")
    return jsonify(
        serialize_stats(
            severity_counts, status_counts, ctx.live.snapshot(), total, demo=ctx.config.demo
        )
    )


# --------------------------------------------------------------------------
# Live buffers
# --------------------------------------------------------------------------
@api.get("/events")
def events():
    """Recent normalized events from the live buffer.

    Events are not persisted by SentinelForge -- the incident store keeps
    incidents, not raw telemetry -- so this endpoint serves the bounded
    in-memory window fed by the file tailers or demo feeder, newest first.
    """
    ctx = context()
    limit, offset = _pagination()
    severity = _choice_arg("severity", Severity.ALL)
    event_type = request.args.get("type") or None
    host = request.args.get("host") or None
    query = request.args.get("q") or None

    items = [dict(item["payload"], sequence=item["sequence"]) for item in ctx.live.recent_activity(ctx.live.buffer_size)]
    items = [item for item in items if "event_type" in item]
    if severity:
        items = [item for item in items if item.get("severity") == severity]
    if event_type:
        items = [item for item in items if item.get("event_type") == event_type]
    if host:
        items = [item for item in items if item.get("host") == host]
    if query:
        items = [
            item
            for item in items
            if _matches_text(
                (item.get("message"), item.get("process"), item.get("user"), item.get("src_ip")),
                query,
            )
        ]
    return jsonify(
        _page(items, limit, offset, source="live buffer (events are not persisted)")
    )


@api.get("/alerts")
def alerts():
    """Alerts from stored incidents, plus anything currently live.

    Alerts live inside their incident (Phase 3 correlation attaches them), so
    this reads the most recent incidents rather than introducing a second
    alert table.  The number of incidents scanned is bounded by
    ``alert_scan_incidents``.
    """
    ctx = context()
    limit, offset = _pagination()
    severity = _choice_arg("severity", Severity.ALL)
    rule_id = request.args.get("rule") or None
    host = request.args.get("host") or None
    source_ip = request.args.get("source_ip") or None
    since = request.args.get("since") or None
    until = request.args.get("until") or None
    query = request.args.get("q") or None

    try:
        incidents = _load_incidents(ctx.config.alert_scan_incidents)
    except sqlite3.Error as exc:
        return error(503, "store_unavailable", f"cannot read the incident store: {exc}")

    items: list[dict] = []
    for incident in incidents:
        items.extend(incident_alerts(incident))

    if severity:
        items = [item for item in items if item.get("severity") == severity]
    if rule_id:
        items = [item for item in items if item.get("rule_id") == rule_id]
    if host:
        items = [item for item in items if item.get("host") == host]
    if source_ip:
        items = [item for item in items if item.get("source_ip") == source_ip]
    if query:
        items = [
            item
            for item in items
            if _matches_text(
                (item.get("description"), item.get("name"), item.get("rule_id"),
                 item.get("user"), item.get("source_ip"), item.get("host")),
                query,
            )
        ]
    for bound, keep in ((since, lambda a, b: a >= b), (until, lambda a, b: a <= b)):
        if not bound:
            continue
        moment = parse_timestamp(bound)
        if moment is None:
            raise BadRequest(f"invalid timestamp {bound!r} (expected RFC 3339, e.g. 2026-09-13T00:00:00Z)")
        filtered = []
        for item in items:
            stamp = parse_timestamp(item.get("timestamp"))
            if stamp is not None and keep(stamp, moment):
                filtered.append(item)
        items = filtered

    items.sort(key=lambda item: (item.get("timestamp") or "", item.get("alert_id") or ""), reverse=True)
    return jsonify(_page(items, limit, offset, scanned_incidents=len(incidents)))


# --------------------------------------------------------------------------
# Incidents
# --------------------------------------------------------------------------
def _filtered_incidents():
    """Apply the incident list filters, server-side."""
    severity = _choice_arg("severity", Severity.ALL)
    min_severity = _choice_arg("min_severity", Severity.ALL)
    status = _choice_arg("status", IncidentStatus.ALL)
    host = request.args.get("host") or None
    source_ip = request.args.get("source_ip") or None
    technique = request.args.get("technique") or None
    user = request.args.get("user") or None
    min_risk = _int_arg("min_risk", None, minimum=0, maximum=100)
    query = request.args.get("q") or None

    incidents = _load_incidents()
    items = [serialize_incident_summary(incident) for incident in incidents]

    if severity:
        items = [item for item in items if item["severity"] == severity]
    if min_severity:
        items = [item for item in items if Severity.at_least(item["severity"], min_severity)]
    if status:
        items = [item for item in items if item["status"] == status]
    if host:
        items = [item for item in items if item["host"] == host]
    if source_ip:
        items = [item for item in items if source_ip in (item["source_ips"] or [])]
    if user:
        items = [item for item in items if user in (item["users"] or [])]
    if technique:
        wanted = technique.upper()
        items = [
            item
            for item in items
            if any(str(code).upper().startswith(wanted) for code in item["techniques"])
        ]
    if min_risk is not None:
        items = [item for item in items if item["risk_score"] >= min_risk]
    if query:
        items = [
            item
            for item in items
            if _matches_text(
                (item["title"], item["incident_id"], item["host"],
                 " ".join(item["source_ips"]), " ".join(item["users"]),
                 " ".join(item["rule_ids"])),
                query,
            )
        ]

    sort_field = request.args.get("sort") or "last_seen"
    if sort_field not in ("last_seen", "first_seen", "severity", "risk_score", "incident_id", "host", "status"):
        raise BadRequest(f"unknown sort field {sort_field!r}")
    descending = (request.args.get("order") or "desc") != "asc"
    items.sort(key=lambda item: sort_key(item, sort_field), reverse=descending)
    return items


@api.get("/incidents")
def incidents():
    """Incident list with filtering, sorting and pagination."""
    limit, offset = _pagination()
    try:
        items = _filtered_incidents()
    except sqlite3.Error as exc:
        return error(503, "store_unavailable", f"cannot read the incident store: {exc}")
    return jsonify(_page(items, limit, offset))


def _get_incident(incident_id: str):
    """Load one incident, or return an error response tuple.

    Returns ``(incident, None)`` on success and ``(None, response)`` otherwise,
    so every incident endpoint handles a malformed id (400), an unknown id
    (404) and an unreadable database (503) the same way.
    """
    if not INCIDENT_ID_PATTERN.match(incident_id or ""):
        return None, error(
            400,
            "invalid_incident_id",
            "incident ids look like INC-000001",
            received=incident_id,
        )
    try:
        with context().store() as store:
            incident = store.get(incident_id)
    except sqlite3.Error as exc:
        return None, error(503, "store_unavailable", f"cannot read the incident store: {exc}")
    if incident is None:
        return None, error(404, "incident_not_found", f"no such incident: {incident_id}")
    return incident, None


@api.get("/incidents/<incident_id>")
def incident_detail(incident_id: str):
    """Everything about one incident, in the shape the detail page uses."""
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    return jsonify(serialize_incident_detail(incident))


@api.get("/incidents/<incident_id>/timeline")
def incident_timeline(incident_id: str):
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    limit = _int_arg("limit", None, minimum=1, maximum=context().config.max_page_size)
    return jsonify(serialize_timeline(incident, limit=limit))


@api.get("/incidents/<incident_id>/attack-chain")
def incident_attack_chain(incident_id: str):
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    return jsonify(serialize_attack_chain(incident))


@api.get("/incidents/<incident_id>/process-tree")
def incident_process_tree(incident_id: str):
    """Process lineage, or an explicit "no telemetry" answer (200, not 404)."""
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    return jsonify(serialize_process_tree(incident))


@api.get("/incidents/<incident_id>/network")
def incident_network(incident_id: str):
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    return jsonify(serialize_network(incident))


@api.get("/incidents/<incident_id>/alerts")
def incident_alert_list(incident_id: str):
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    evidence = request.args.get("evidence", "0") in ("1", "true", "yes")
    return jsonify(
        {
            "incident_id": incident.incident_id,
            "items": incident_alerts(incident, include_evidence=evidence),
            "total": incident.alert_count,
        }
    )


@api.get("/incidents/<incident_id>/ai")
def incident_ai(incident_id: str):
    """The stored AI analysis, or a 200 saying there is none.

    A missing analysis is a normal state, not an error: incidents exist without
    one, and the dashboard must not imply that the AI layer failed when nobody
    has asked it anything.
    """
    incident, failure = _get_incident(incident_id)
    if failure:
        return failure
    return jsonify(serialize_ai_analysis(incident))


# --------------------------------------------------------------------------
# ATT&CK and sensors
# --------------------------------------------------------------------------
@api.get("/mitre")
def mitre():
    """ATT&CK techniques seen across stored incidents.

    Mappings come from the detection rules (Phase 2's validated catalogue).
    The dashboard aggregates; it never invents a technique.
    """
    incident_id = request.args.get("incident_id")
    if incident_id:
        incident, failure = _get_incident(incident_id)
        if failure:
            return failure
        incidents_list = [incident]
    else:
        try:
            incidents_list = _load_incidents()
        except sqlite3.Error as exc:
            return error(503, "store_unavailable", f"cannot read the incident store: {exc}")
    items = mitre_breakdown(incidents_list)
    return jsonify(
        {
            "items": items,
            "total": len(items),
            "incident_count": len(incidents_list),
            "api_version": API_VERSION,
        }
    )


@api.get("/sensors")
def sensors():
    """Telemetry source availability, including the AI provider."""
    ctx = context()
    items = ctx.sensor_snapshot()
    return jsonify(
        {
            "items": items,
            "total": len(items),
            "online": sum(1 for item in items if item["available"]),
            "monitors": ctx.monitors.describe() if ctx.monitors else [],
            "api_version": API_VERSION,
        }
    )
