"""Input validation for response actions (Phase 7).

This module is the narrow gate every containment target has to pass through.
It exists because of one rule stated in the README: **no string that came from
a log line, a telemetry field, an AI answer or an HTTP body is ever allowed to
influence what SentinelForge executes.**

The way that rule is enforced here is *parsing, not filtering*.  A target is
not "checked for dangerous characters" and then passed along as text -- it is
parsed into a typed value (an :class:`ipaddress.IPv4Address`, an ``int``) and
only the re-rendered typed value is used afterwards.  A payload such as::

    203.0.113.50; rm -rf /

is not escaped, quoted or stripped; it simply fails to parse as an IP address
and the request is refused.  Nothing downstream ever sees it.

The functions here answer "is this a usable target?"  Whether a *usable* target
is an *allowed* one -- loopback, the default gateway, PID 1 -- is a policy
question, and lives in :mod:`sentinelforge.response.policy`.  This module only
supplies the facts that policy reasons about.
"""

from __future__ import annotations

import ipaddress
import os
import re
import socket

#: Longest accepted free-text reason.  Bounded because it is stored, rendered
#: and audited.
MAX_REASON = 500

#: Longest accepted operator label.
MAX_ACTOR = 64

#: Operator labels are names, not free text: a local username or a short
#: identifier.  Anything else is refused rather than sanitized.
ACTOR_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._@ -]{0,63}$")

#: systemd-logind session ids are short and alphanumeric ("2", "c1").
SESSION_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$")

#: Incident ids are generated by SentinelForge; see the Phase 3 model.
INCIDENT_ID_PATTERN = re.compile(r"^INC-\d{1,12}$")

#: Linux PIDs fit in an int; the kernel's ceiling is configurable but small.
MAX_PID = 2**22

#: Bounds for a containment TTL, in seconds.
MIN_TTL = 30
MAX_TTL = 86400


class ValidationError(ValueError):
    """A response target or parameter was not usable.

    Carries a ``field`` so an API can report *which* input was wrong without
    echoing the offending value back into a UI.
    """

    def __init__(self, message: str, field: str = "target") -> None:
        super().__init__(message)
        self.message = message
        self.field = field


# --------------------------------------------------------------------------
# IP addresses
# --------------------------------------------------------------------------
def validate_ip(value: object) -> ipaddress.IPv4Address | ipaddress.IPv6Address:
    """Parse ``value`` into an IP address object, or raise :class:`ValidationError`.

    Accepts a plain IPv4 or IPv6 address.  Rejects anything else, including
    hostnames (no DNS lookup is ever performed: resolving a name supplied by
    telemetry would let an attacker choose what gets blocked), CIDR ranges,
    ports, scoped addresses and every form of shell metacharacter.
    """
    if isinstance(value, (ipaddress.IPv4Address, ipaddress.IPv6Address)):
        return value
    if not isinstance(value, str):
        raise ValidationError(f"IP target must be a string, got {type(value).__name__}", "target")
    text = value.strip()
    if not text:
        raise ValidationError("IP target is empty", "target")
    if len(text) > 45:  # longest possible textual IPv6 address
        raise ValidationError("IP target is too long to be an address", "target")
    if "%" in text:
        raise ValidationError("scoped IPv6 addresses are not accepted as targets", "target")
    try:
        return ipaddress.ip_address(text)
    except ValueError:
        pass
    # Give the one genuinely common mistake its own message; everything else is
    # simply not an address.
    head = text.split("/", 1)[0]
    if "/" in text and _parses_as_ip(head):
        raise ValidationError(
            "IP target must be a single address, not a network/CIDR range", "target"
        )
    raise ValidationError(f"not a valid IP address: {text!r}", "target")


def _parses_as_ip(text: str) -> bool:
    try:
        ipaddress.ip_address(text)
    except ValueError:
        return False
    return True


def classify_ip(address) -> dict:
    """Describe an address for the policy engine.

    Returns plain booleans plus the facts that required looking at this host:
    whether the address belongs to this machine, and whether it is the default
    gateway.  Blocking either would cut the analyst off from the system they
    are defending, which is why policy refuses both.
    """
    address = validate_ip(address)
    text = str(address)
    is_broadcast = address.version == 4 and (
        text == "255.255.255.255" or address == ipaddress.IPv4Address("255.255.255.255")
    )
    return {
        "address": text,
        "version": address.version,
        "is_loopback": bool(address.is_loopback),
        "is_multicast": bool(address.is_multicast),
        "is_unspecified": bool(address.is_unspecified),
        "is_reserved": bool(address.is_reserved),
        "is_link_local": bool(address.is_link_local),
        "is_broadcast": bool(is_broadcast),
        "is_private": bool(address.is_private),
        "is_local_host_address": text in local_addresses(),
        "is_default_gateway": text in default_gateways(),
    }


def local_addresses() -> frozenset[str]:
    """Addresses that belong to this host, as far as it can tell.

    Two stdlib sources, both read-only and neither of them a subprocess:
    resolving this machine's own hostname, and asking the kernel which source
    address it would use to reach the outside world.  The second uses a
    *connectionless* UDP socket -- ``connect()`` on ``SOCK_DGRAM`` only sets the
    peer for the routing lookup, it transmits nothing -- so probing this costs
    no traffic and touches no other host.

    Best effort by design: a missed address means policy asks the analyst to
    confirm, never that a wrong rule is silently installed.
    """
    found: set[str] = {"127.0.0.1", "::1"}
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None):
            candidate = info[4][0]
            if isinstance(candidate, str):
                found.add(candidate.split("%", 1)[0])
    except (socket.gaierror, OSError, UnicodeError):  # pragma: no cover - depends on DNS
        pass
    for family, probe in ((socket.AF_INET, "192.0.2.1"), (socket.AF_INET6, "2001:db8::1")):
        # TEST-NET-1 / the documentation prefix: reserved for examples, routed
        # nowhere.  Used purely as a routing hint.
        try:
            with socket.socket(family, socket.SOCK_DGRAM) as probe_socket:
                probe_socket.connect((probe, 9))
                found.add(probe_socket.getsockname()[0].split("%", 1)[0])
        except OSError:  # pragma: no cover - no route for that family
            continue
    return frozenset(found)


def default_gateways(proc_route: str = "/proc/net/route") -> frozenset[str]:
    """The IPv4 default gateway(s), read from ``/proc/net/route``.

    A plain file read: no ``ip route``, no subprocess.  The file stores the
    destination and gateway as little-endian hex, and a default route is the
    one whose destination is ``00000000``.

    IPv6 default gateways are not parsed; see the README's "Known limitations".
    """
    gateways: set[str] = set()
    try:
        with open(proc_route, "r", encoding="utf-8", errors="replace") as handle:
            next(handle, None)  # header row
            for line in handle:
                fields = line.split()
                if len(fields) < 3 or fields[1] != "00000000":
                    continue
                try:
                    packed = int(fields[2], 16).to_bytes(4, "little")
                except (ValueError, OverflowError):
                    continue
                gateway = ipaddress.IPv4Address(packed)
                if not gateway.is_unspecified:
                    gateways.add(str(gateway))
    except (OSError, StopIteration):  # pragma: no cover - not Linux, or unreadable
        return frozenset()
    return frozenset(gateways)


# --------------------------------------------------------------------------
# Processes and sessions
# --------------------------------------------------------------------------
def validate_pid(value: object) -> int:
    """Parse ``value`` into a PID, or raise :class:`ValidationError`.

    Accepts an ``int`` or a string of digits.  Rejects floats, negative numbers
    (a negative PID means "the whole process group" to ``kill(2)``, which is
    exactly the kind of accidental blast radius this layer exists to prevent),
    zero (the caller's own process group) and anything out of range.
    """
    if isinstance(value, bool):
        raise ValidationError("PID must be a number, not a boolean", "target")
    if isinstance(value, int):
        pid = value
    elif isinstance(value, str):
        text = value.strip()
        if not text or not text.isdigit():
            raise ValidationError(f"not a valid PID: {text!r}", "target")
        try:
            pid = int(text)
        except ValueError:  # pragma: no cover - isdigit() already guarantees this
            raise ValidationError(f"not a valid PID: {text!r}", "target") from None
    else:
        raise ValidationError(f"PID must be an integer, got {type(value).__name__}", "target")

    if pid <= 0:
        raise ValidationError(
            "PID must be a positive integer (0 and negative values address whole "
            "process groups and are never valid response targets)",
            "target",
        )
    if pid > MAX_PID:
        raise ValidationError(f"PID {pid} is out of range", "target")
    return pid


def validate_session_id(value: object) -> str:
    """Parse a systemd-logind session id."""
    if not isinstance(value, str):
        raise ValidationError(
            f"session id must be a string, got {type(value).__name__}", "target"
        )
    text = value.strip()
    if not SESSION_ID_PATTERN.match(text):
        raise ValidationError(f"not a valid session id: {text!r}", "target")
    return text


# --------------------------------------------------------------------------
# Request metadata
# --------------------------------------------------------------------------
def validate_action_type(value: object) -> str:
    """Check an action type against the known vocabulary."""
    from .models import ActionType

    if not isinstance(value, str) or not ActionType.is_valid(value):
        raise ValidationError(
            f"unknown action type {value!r} (known: {', '.join(ActionType.ALL)})",
            "action_type",
        )
    return value


def validate_incident_id(value: object, allow_none: bool = True) -> str | None:
    """Check an incident id against the Phase 3 id format."""
    if value in (None, ""):
        if allow_none:
            return None
        raise ValidationError("an incident id is required", "incident_id")
    if not isinstance(value, str) or not INCIDENT_ID_PATTERN.match(value):
        raise ValidationError(f"not a valid incident id: {value!r}", "incident_id")
    return value


def validate_reason(value: object, required: bool = False) -> str:
    """Bound and clean the operator's free-text justification.

    Control characters are removed because this string is written to a database
    and rendered in a terminal; it is never interpreted.
    """
    if value in (None, ""):
        if required:
            raise ValidationError("a reason is required for this action", "reason")
        return ""
    if not isinstance(value, str):
        raise ValidationError(f"reason must be text, got {type(value).__name__}", "reason")
    cleaned = "".join(ch for ch in value if ch == " " or ch.isprintable()).strip()
    if required and not cleaned:
        raise ValidationError("a reason is required for this action", "reason")
    return cleaned[:MAX_REASON]


def validate_actor(value: object, field: str = "requested_by") -> str:
    """Check an operator label (who asked for this, who approved it)."""
    if value in (None, ""):
        return default_actor()
    if not isinstance(value, str):
        raise ValidationError(f"{field} must be text", field)
    text = value.strip()
    if len(text) > MAX_ACTOR or not ACTOR_PATTERN.match(text):
        raise ValidationError(
            f"{field} must be a short operator name "
            "(letters, digits, dot, dash, underscore, @ or space)",
            field,
        )
    return text


def default_actor() -> str:
    """The local operator's name, used when a caller does not supply one."""
    for source in (os.environ.get("SUDO_USER"), os.environ.get("USER")):
        if source and ACTOR_PATTERN.match(source):
            return source
    try:
        import pwd

        return pwd.getpwuid(os.getuid()).pw_name
    except Exception:  # pragma: no cover - no passwd database
        return "unknown"


def validate_ttl(value: object, allow_none: bool = True) -> int | None:
    """Check a containment lifetime in seconds."""
    if value in (None, ""):
        if allow_none:
            return None
        raise ValidationError("a TTL is required for this action", "ttl")
    if isinstance(value, bool):
        raise ValidationError("ttl must be a number of seconds", "ttl")
    if isinstance(value, str):
        text = value.strip()
        if not text.isdigit():
            raise ValidationError(f"ttl must be a whole number of seconds, got {text!r}", "ttl")
        value = int(text)
    if not isinstance(value, int):
        raise ValidationError("ttl must be a whole number of seconds", "ttl")
    if value < MIN_TTL:
        raise ValidationError(f"ttl must be at least {MIN_TTL} seconds", "ttl")
    if value > MAX_TTL:
        raise ValidationError(f"ttl must be at most {MAX_TTL} seconds ({MAX_TTL // 3600}h)", "ttl")
    return value


def validate_action_id(value: object) -> str:
    """Check an action id against the format this phase generates."""
    if not isinstance(value, str) or not re.match(r"^ACTION-\d{1,12}$", value):
        raise ValidationError(f"not a valid action id: {value!r}", "action_id")
    return value
